# version: '3.1'
#
# services:
#   wordpress:
#     depends_on:
#       - mysql
#     environment:
#       WORDPRESS_DB_HOST: mysql:3306
#       WORDPRESS_DB_PASSWORD: wordpress
#       WORDPRESS_DB_USER: wordpress
#     image: wordpress:4.9.6-php7.2-fpm-alpine
#     ports:
#       - '8000:80'
#     links:
#       - mysql
#     restart: always
#
#   mysql:
#     environment:
#       MYSQL_ROOT_PASSWORD: wordpress
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wordpress
#       MYSQL_PASSWORD: wordpress
#     image: mysql:8
#     restart: always
#     volumes:
#         - mysql-data:/var/lib/mysql
#
# volumes:
#   mysql-data:

version: '3.3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes

volumes:
  db_data:
